# totally useless - just learning
language: c
os: linux

sudo: false

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install luacov
  - luarocks install tapered

script:
  - lua -lluacov awesome-tests.lua

after_success:
  - bash <(curl -s https://codecov.io/bash)
